spring:
  application:
    name: google-login

server:
  port: 8080

aws:
  region: us-east-1
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
dynamodb:
  image-table: ${DYNAMODB_IMAGE_TABLE}
  user-table: ${DYNAMODB_USER_TABLE}
s3:
  input-bucket: ${S3_INPUT_BUCKET}
  output-bucket: ${S3_OUTPUT_BUCKET}

google:
  client-id: ${GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
